name: Deploy to EC2

on:
  workflow_dispatch:  # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Transfer code to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  
          username: ${{ secrets.EC2_USERNAME }}  
          key: ${{ secrets.EC2_SSH_KEY }}  
          source: .  # Copy all files from the repository root
          target: /home/ubuntu/app/next/  

      - name: SSH into EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  
          username: ${{ secrets.EC2_USERNAME }}  
          key: ${{ secrets.EC2_SSH_KEY }}  
          script: |
            cd /home/ubuntu/app
            cd next
            PATH=$PATH:/home/${{secrets.EC2_USERNAME}}/.nvm/versions/node/v18.16.0/bin 
            sudo npm run build
            PATH=$PATH:/home/${{secrets.EC2_USERNAME}}/.nvm/versions/node/v18.16.0/bin/pm2
            sudo pm2 restart 0
