name: Deploy to EC2

on:
  workflow_dispatch:  # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Transfer code to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  
          username: ${{ secrets.EC2_USERNAME }}  
          key: ${{ secrets.EC2_SSH_KEY }}  
          source: .  # Copy all files from the repository root
          target: /home/ubuntu/app/next/  
      
      - name: SSH into EC2 and Run Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  
          username: ${{ secrets.EC2_USERNAME }}  
          key: ${{ secrets.EC2_SSH_KEY }}  
          script: /home/ubuntu/app/next/next.sh
          shell: bash

        
